### ISSUE TITLE
Feedback loop

### ISSUE THREAD

**Issue by jianyangg** [jianyangg/local-llm#20]
For the agentic workflow, we are only relying on the temperature setting of the llm to generate a different response. Instead, we want the agents to give and receive feedback so that answer can be evaluated by each grading agent which may improve the answer iteratively.

**Comment by hanchingyong** [comment]
still want do this? can be a good to have bah

**Comment by jianyangg** [comment]
Currently it leads to an infinite loop since there's no feedback given to alter the question, might help to leave feedback in graph state!

**Comment by jianyangg** [comment]
Fixed in #23 .
